//! Day/night cycle: a real-time clock (20-minute days, 10-minute nights,
//! see [`DAY_SECONDS`]/[`NIGHT_SECONDS`]) driving a sun and a moon that rise
//! due east and set due west - this engine's established compass mapping
//! (`blocks.rs`'s face-order doc: +X east, -X west, -Z north, +Z south) -
//! arcing straight overhead through the zenith. Only one is ever up at a
//! time: the sun for the whole day phase, the moon for the whole night
//! phase, each completing its entire rise-to-set arc within its own phase's
//! duration.
//!
//! Both are flat, always-camera-facing quads (billboards) orbiting the
//! camera at a fixed radius - the same "attached to the sky, not the world"
//! trick real-time-strategy/voxel games have used forever, cheap because it
//! needs no new geometry per chunk and no dynamic light source at all.
//!
//! This is a fully unlit renderer (see `render.rs`'s module docs): there's
//! no real light to dim at night, so `update_sky` instead writes a single
//! global brightness multiplier (`render::ChunkMaterialParams::sky_light`)
//! into both chunk materials every frame, plus the sky/fog color - cheap
//! (two tiny uniform writes, no remeshing) despite touching the whole
//! world's apparent lighting at once.
//!
//! Sun/moon textures are procedurally generated by default (this module),
//! exactly like block textures (`atlas.rs`) - drop a `textures/sky/sun.png`
//! or `textures/sky/moon.png` to override one with real art instead; no
//! code changes, no recompile. Unlike the block atlas there's no shared
//! resolution or tile-packing to keep in sync, since each is one standalone
//! sprite - any square PNG is used at its own native size.
//!
//! The clock persists per-world (`save::WorldData::time_of_day`) so leaving
//! and reloading resumes rather than resetting to dawn - the same
//! don't-silently-lose-continuous-state-on-reload lesson as fluids (see
//! CLAUDE.md).

use bevy::asset::embedded_asset;
use bevy::color::Mix;
use bevy::pbr::{MaterialPipeline, MaterialPipelineKey};
use bevy::prelude::*;
use bevy::render::mesh::{Indices, MeshVertexBufferLayoutRef, PrimitiveTopology};
use bevy::render::render_asset::RenderAssetUsages;
use bevy::render::render_resource::{
    AsBindGroup, Extent3d, RenderPipelineDescriptor, ShaderRef, ShaderType,
    SpecializedMeshPipelineError, TextureDimension, TextureFormat,
};
use std::f32::consts::{PI, TAU};
use std::path::{Path, PathBuf};

use crate::config::{WorldSettings, CHUNK_SIZE, SKY_COLOR};
use crate::noise::{hash_str, mulberry32};
use crate::player::Player;
use crate::render::{ChunkMaterial, ChunkMaterials};
use crate::state::AppState;

pub const DAY_SECONDS: f32 = 20.0 * 60.0;
pub const NIGHT_SECONDS: f32 = 10.0 * 60.0;
pub const CYCLE_SECONDS: f32 = DAY_SECONDS + NIGHT_SECONDS;

/// Night's sky/fog color and the world's darkest brightness floor - never
/// fully black, matching the softly-lit look everything else in this
/// renderer already has.
const NIGHT_SKY: Color = Color::srgb(0.03, 0.04, 0.09);
const NIGHT_LIGHT: f32 = 0.22;
const DAY_LIGHT: f32 = 1.0;

/// The sun/moon's orbit radius and quad size, both expressed as a fraction
/// of the camera's far clip plane - sits comfortably inside it (so it's
/// never culled) regardless of `render_distance`.
const ORBIT_FRAC_OF_FAR: f32 = 0.85;
const SIZE_FRAC_OF_RADIUS: f32 = 0.12;

/// Native resolution of a procedurally generated sun/moon texture. A custom
/// `textures/sky/*.png` overrides this with its own size instead.
const SKY_TEXTURE_SIZE: usize = 64;

#[derive(Component)]
struct Sun;

#[derive(Component)]
struct Moon;

/// Real-time position in the day/night cycle. Advances every frame while in
/// a world (`advance_clock`) and is reset from - then kept in sync with -
/// the active world's save data (`world.rs`'s `enter_world`/`write_save`).
#[derive(Resource)]
pub struct DayNightClock {
    /// Seconds into the current `[0, CYCLE_SECONDS)` cycle. `0` is dawn:
    /// the sun exactly on the eastern horizon, about to rise.
    pub elapsed: f32,
}

impl Default for DayNightClock {
    fn default() -> Self {
        Self { elapsed: 0.0 }
    }
}

impl DayNightClock {
    pub fn is_day(&self) -> bool {
        self.elapsed < DAY_SECONDS
    }

    /// 0..1 progress through whichever of day/night is currently active -
    /// `0` right at rise, `1` right at set.
    fn phase_progress(&self) -> f32 {
        if self.is_day() {
            self.elapsed / DAY_SECONDS
        } else {
            (self.elapsed - DAY_SECONDS) / NIGHT_SECONDS
        }
    }

    /// The active body's angle above the eastern horizon: `0` at rise,
    /// `PI` at set, `PI/2` at zenith - see [`celestial_offset`].
    fn phase_angle(&self) -> f32 {
        self.phase_progress() * PI
    }

    /// `0` at rise/set, `1` at zenith. Doubles as both a fade-near-the-
    /// horizon factor and the world's daylight brightness (see
    /// [`Self::daylight`]) - a plain sine naturally eases both smoothly
    /// through sunrise/sunset with no separate interpolation needed.
    fn phase_height(&self) -> f32 {
        self.phase_angle().sin().max(0.0)
    }

    /// How daylit the world is right now: `0` at the depths of night up to
    /// `1` at high noon, driven entirely by the sun's height so sunrise and
    /// sunset ease naturally. Pinned to `0` for the whole night phase - the
    /// moon lights nothing, it just lets you see it's up.
    pub fn daylight(&self) -> f32 {
        if self.is_day() {
            self.phase_height()
        } else {
            0.0
        }
    }
}

/// East-to-west arc offset from the camera for `angle` (`0` = due east
/// horizon, `PI/2` = zenith, `PI` = due west horizon) at `radius` - a plain
/// overhead great circle, ignoring latitude/season for simplicity (see the
/// module docs for the compass mapping this relies on).
fn celestial_offset(angle: f32, radius: f32) -> Vec3 {
    Vec3::new(angle.cos() * radius, angle.sin() * radius, 0.0)
}

#[derive(Clone, ShaderType)]
#[allow(dead_code)] // the ShaderType derive generates per-field check fns
struct CelestialParams {
    tint: LinearRgba,
}

#[derive(Asset, TypePath, AsBindGroup, Clone)]
struct CelestialMaterial {
    #[texture(0)]
    #[sampler(1)]
    texture: Handle<Image>,
    #[uniform(2)]
    params: CelestialParams,
}

impl Material for CelestialMaterial {
    fn fragment_shader() -> ShaderRef {
        "embedded://craftmjne/celestial.wgsl".into()
    }

    fn alpha_mode(&self) -> AlphaMode {
        AlphaMode::Blend
    }

    fn specialize(
        _pipeline: &MaterialPipeline<Self>,
        descriptor: &mut RenderPipelineDescriptor,
        _layout: &MeshVertexBufferLayoutRef,
        _key: MaterialPipelineKey<Self>,
    ) -> Result<(), SpecializedMeshPipelineError> {
        // A billboard has no "back" worth culling - it's always turned to
        // face the camera, but cheaply skipping the exact winding-order
        // math to guarantee that is one less thing to get subtly wrong.
        descriptor.primitive.cull_mode = None;
        Ok(())
    }
}

#[derive(Resource)]
struct SkyMaterials {
    sun: Handle<CelestialMaterial>,
    moon: Handle<CelestialMaterial>,
}

/// A unit quad in the XY plane, centered on the origin - scaled to its
/// final size per-frame via `Transform::scale` (see `update_sky`), since
/// that size depends on `WorldSettings::render_distance`, which can change
/// after this mesh is built. Carries a uniform white vertex color purely to
/// match `render::bucket_to_mesh`'s proven-working attribute set (position +
/// UV + color, no normals) rather than risk an untested minimal layout.
fn quad_mesh() -> Mesh {
    let mut mesh = Mesh::new(PrimitiveTopology::TriangleList, RenderAssetUsages::default());
    mesh.insert_attribute(
        Mesh::ATTRIBUTE_POSITION,
        vec![[-0.5, -0.5, 0.0], [0.5, -0.5, 0.0], [0.5, 0.5, 0.0], [-0.5, 0.5, 0.0]],
    );
    mesh.insert_attribute(
        Mesh::ATTRIBUTE_UV_0,
        vec![[0.0, 1.0], [1.0, 1.0], [1.0, 0.0], [0.0, 0.0]],
    );
    mesh.insert_attribute(
        Mesh::ATTRIBUTE_COLOR,
        vec![[1.0, 1.0, 1.0, 1.0]; 4],
    );
    mesh.insert_indices(Indices::U32(vec![0, 1, 2, 0, 2, 3]));
    mesh
}

/// Where to look for `textures/sky/`: next to the running executable first
/// (how an installed/shipped build finds files shipped next to it), falling
/// back to the current working directory (how `cargo run`/tests find one at
/// the repo root). Mirrors `atlas::find_textures_dir`/`blocks::find_blocks_dir`
/// exactly.
fn find_sky_dir() -> PathBuf {
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let candidate = dir.join("textures").join("sky");
            if candidate.is_dir() {
                return candidate;
            }
        }
    }
    PathBuf::from("textures").join("sky")
}

/// Loads `<dir>/<name>.png` if present, decoded to raw RGBA8 plus its
/// (square) size - `None` if the file just isn't there, so the procedural
/// texture is used instead. Panics on a malformed file (not square,
/// unreadable/corrupt), matching `atlas::load_custom_tile`'s "a broken file
/// is a mistake worth surfacing loudly, not papering over" precedent.
fn load_custom_sky_texture(dir: &Path, name: &str) -> Option<(Vec<u8>, u32)> {
    let path = dir.join(format!("{name}.png"));
    if !path.is_file() {
        return None;
    }
    let img = image::open(&path)
        .unwrap_or_else(|err| panic!("failed to read texture {path:?}: {err}"))
        .into_rgba8();
    let (w, h) = (img.width(), img.height());
    if w != h {
        panic!("texture {path:?} is {w}x{h}, but sun/moon textures must be square");
    }
    Some((img.into_raw(), w))
}

/// A checkered-disc "moon crater" placement helper: `n` deterministic
/// (x, y, radius) blobs scattered within `radius * 0.65` of center, seeded
/// from `rng` so a fresh call each startup is reproducible run-to-run.
fn scatter_craters(rng: &mut dyn FnMut() -> f32, n: usize, center: f32, radius: f32) -> Vec<(f32, f32, f32)> {
    (0..n)
        .map(|_| {
            let a = rng() * TAU;
            let d = rng() * radius * 0.65;
            let cr = radius * (0.12 + rng() * 0.1);
            (center + a.cos() * d, center + a.sin() * d, cr)
        })
        .collect()
}

/// A warm gold disc, brightest at the center and deepening toward a soft
/// orange rim, fully transparent outside its radius.
fn generate_sun_pixels(size: usize) -> Vec<u8> {
    let mut rng = mulberry32(hash_str("sun"));
    let mut pixels = vec![0u8; size * size * 4];
    let center = (size as f32 - 1.0) * 0.5;
    let radius = size as f32 * 0.48;
    for y in 0..size {
        for x in 0..size {
            let dx = x as f32 - center;
            let dy = y as f32 - center;
            let dist = (dx * dx + dy * dy).sqrt();
            if dist > radius {
                continue; // stays fully transparent - the buffer starts zeroed
            }
            let t = (dist / radius).clamp(0.0, 1.0);
            let jitter = (rng() - 0.5) * 18.0;
            let r = (255.0 - t * 25.0 + jitter).clamp(0.0, 255.0);
            let g = (214.0 - t * 60.0 + jitter).clamp(0.0, 255.0);
            let b = (110.0 - t * 70.0 + jitter * 0.5).clamp(0.0, 255.0);
            let i = (y * size + x) * 4;
            pixels[i] = r as u8;
            pixels[i + 1] = g as u8;
            pixels[i + 2] = b as u8;
            pixels[i + 3] = 255;
        }
    }
    pixels
}

/// A pale gray-white disc with a handful of darker craters, fully
/// transparent outside its radius.
fn generate_moon_pixels(size: usize) -> Vec<u8> {
    let mut rng = mulberry32(hash_str("moon"));
    let mut pixels = vec![0u8; size * size * 4];
    let center = (size as f32 - 1.0) * 0.5;
    let radius = size as f32 * 0.48;
    let craters = scatter_craters(&mut rng, 6, center, radius);
    for y in 0..size {
        for x in 0..size {
            let dx = x as f32 - center;
            let dy = y as f32 - center;
            let dist = (dx * dx + dy * dy).sqrt();
            if dist > radius {
                continue;
            }
            let jitter = (rng() - 0.5) * 10.0;
            let mut c = 222.0 + jitter;
            for &(cx, cy, cr) in &craters {
                let cd = ((x as f32 - cx).powi(2) + (y as f32 - cy).powi(2)).sqrt();
                if cd < cr {
                    c -= (1.0 - cd / cr) * 45.0;
                }
            }
            let c = c.clamp(60.0, 255.0);
            let i = (y * size + x) * 4;
            pixels[i] = c as u8;
            pixels[i + 1] = c as u8;
            pixels[i + 2] = (c * 0.97) as u8;
            pixels[i + 3] = 255;
        }
    }
    pixels
}

fn sky_texture(dir: &Path, name: &str, procedural: fn(usize) -> Vec<u8>) -> (Vec<u8>, u32) {
    load_custom_sky_texture(dir, name)
        .unwrap_or_else(|| (procedural(SKY_TEXTURE_SIZE), SKY_TEXTURE_SIZE as u32))
}

fn upload_sky_image(pixels: Vec<u8>, size: u32) -> Image {
    Image::new(
        Extent3d { width: size, height: size, depth_or_array_layers: 1 },
        TextureDimension::D2,
        pixels,
        TextureFormat::Rgba8UnormSrgb,
        RenderAssetUsages::default(),
    )
    // Deliberately not nearest-sampled (unlike the block atlas): these are
    // smooth gradient discs, not pixel art, so the default linear filtering
    // is what makes the edge and shading actually look round.
}

/// Startup: generates (or loads custom) sun/moon textures, and spawns both
/// as hidden billboards - `update_sky` takes over their position, facing,
/// and visibility every frame once a world's loaded.
fn spawn_sky(
    mut commands: Commands,
    mut images: ResMut<Assets<Image>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<CelestialMaterial>>,
) {
    let dir = find_sky_dir();
    let (sun_pixels, sun_size) = sky_texture(&dir, "sun", generate_sun_pixels);
    let (moon_pixels, moon_size) = sky_texture(&dir, "moon", generate_moon_pixels);

    let sun_handle = images.add(upload_sky_image(sun_pixels, sun_size));
    let moon_handle = images.add(upload_sky_image(moon_pixels, moon_size));
    let mesh = meshes.add(quad_mesh());

    let sun = materials.add(CelestialMaterial {
        texture: sun_handle,
        params: CelestialParams { tint: LinearRgba::WHITE },
    });
    let moon = materials.add(CelestialMaterial {
        texture: moon_handle,
        params: CelestialParams { tint: LinearRgba::WHITE },
    });

    commands.spawn((Sun, Mesh3d(mesh.clone()), MeshMaterial3d(sun.clone()), Visibility::Hidden));
    commands.spawn((Moon, Mesh3d(mesh), MeshMaterial3d(moon.clone()), Visibility::Hidden));
    commands.insert_resource(SkyMaterials { sun, moon });
}

fn advance_clock(time: Res<Time>, mut clock: ResMut<DayNightClock>) {
    clock.elapsed = (clock.elapsed + time.delta_secs()).rem_euclid(CYCLE_SECONDS);
}

/// Every frame: positions/orients whichever of the sun or moon is
/// currently up (orbiting the camera, always facing it), fades it in/out
/// near the horizon, and writes the day/night-driven sky color + chunk
/// brightness (`render::ChunkMaterialParams::sky_light`) - see the module
/// docs for why a single global multiplier is this renderer's stand-in for
/// a real light source.
#[allow(clippy::too_many_arguments)]
fn update_sky(
    clock: Res<DayNightClock>,
    settings: Res<WorldSettings>,
    sky_materials: Res<SkyMaterials>,
    chunk_materials: Res<ChunkMaterials>,
    camera: Query<&Transform, (With<Player>, Without<Sun>, Without<Moon>)>,
    mut sun: Query<(&mut Transform, &mut Visibility), (With<Sun>, Without<Moon>, Without<Player>)>,
    mut moon: Query<(&mut Transform, &mut Visibility), (With<Moon>, Without<Sun>, Without<Player>)>,
    mut clear_color: ResMut<ClearColor>,
    mut celestial_assets: ResMut<Assets<CelestialMaterial>>,
    mut chunk_assets: ResMut<Assets<ChunkMaterial>>,
) {
    let Ok(camera_tf) = camera.single() else { return };
    let Ok((mut sun_tf, mut sun_vis)) = sun.single_mut() else { return };
    let Ok((mut moon_tf, mut moon_vis)) = moon.single_mut() else { return };

    let far = (settings.render_distance * CHUNK_SIZE) as f32 * 2.0;
    let radius = far * ORBIT_FRAC_OF_FAR;
    let size = radius * SIZE_FRAC_OF_RADIUS;

    let offset = celestial_offset(clock.phase_angle(), radius);
    let pos = camera_tf.translation + offset;
    // Both bodies are radially symmetric discs, so any roll around the
    // view axis looks identical - `from_rotation_arc` (unlike
    // `Transform::looking_at`) needs no separate up vector and so has no
    // degenerate case at the zenith, where the look direction is exactly
    // parallel to world-up.
    let facing = Quat::from_rotation_arc(Vec3::NEG_Z, (camera_tf.translation - pos).normalize());
    // Never fully transparent while up - fades toward the horizon instead
    // of an abrupt pop into/out of existence at the exact rise/set instant.
    let fade = clock.phase_height() * 0.7 + 0.3;

    let is_day = clock.is_day();

    *sun_vis = if is_day { Visibility::Visible } else { Visibility::Hidden };
    if is_day {
        sun_tf.translation = pos;
        sun_tf.scale = Vec3::splat(size);
        sun_tf.rotation = facing;
    }
    if let Some(mat) = celestial_assets.get_mut(&sky_materials.sun) {
        mat.params.tint.alpha = if is_day { fade } else { 0.0 };
    }

    *moon_vis = if is_day { Visibility::Hidden } else { Visibility::Visible };
    if !is_day {
        moon_tf.translation = pos;
        moon_tf.scale = Vec3::splat(size);
        moon_tf.rotation = facing;
    }
    if let Some(mat) = celestial_assets.get_mut(&sky_materials.moon) {
        mat.params.tint.alpha = if !is_day { fade } else { 0.0 };
    }

    let daylight = clock.daylight();
    let sky_color = NIGHT_SKY.mix(&SKY_COLOR, daylight);
    clear_color.0 = sky_color;
    let fog_color = LinearRgba::from(sky_color);
    let sky_light = NIGHT_LIGHT + (DAY_LIGHT - NIGHT_LIGHT) * daylight;
    for handle in [&chunk_materials.solid, &chunk_materials.water] {
        if let Some(mat) = chunk_assets.get_mut(handle) {
            mat.params.fog_color = fog_color;
            mat.params.sky_light = sky_light;
        }
    }
}

pub struct SkyPlugin;

impl Plugin for SkyPlugin {
    fn build(&self, app: &mut App) {
        embedded_asset!(app, "celestial.wgsl");
        app.add_plugins(MaterialPlugin::<CelestialMaterial>::default())
            .init_resource::<DayNightClock>()
            .add_systems(Startup, spawn_sky)
            .add_systems(
                Update,
                (advance_clock, update_sky)
                    .chain()
                    .run_if(in_state(AppState::InGame)),
            );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_fresh_clock_starts_at_dawn() {
        let clock = DayNightClock::default();
        assert!(clock.is_day());
        assert_eq!(clock.phase_progress(), 0.0);
        assert_eq!(clock.daylight(), 0.0); // sun is exactly on the horizon
    }

    #[test]
    fn the_clock_stays_within_one_cycle_and_wraps_smoothly() {
        let mut clock = DayNightClock { elapsed: CYCLE_SECONDS - 1.0 };
        clock.elapsed = (clock.elapsed + 2.0).rem_euclid(CYCLE_SECONDS);
        assert!((clock.elapsed - 1.0).abs() < 1e-4, "expected to wrap just past 0, got {}", clock.elapsed);
    }

    #[test]
    fn day_lasts_exactly_twenty_minutes_and_night_ten() {
        assert_eq!(DAY_SECONDS, 1200.0);
        assert_eq!(NIGHT_SECONDS, 600.0);
        let mut clock = DayNightClock { elapsed: DAY_SECONDS - 0.001 };
        assert!(clock.is_day());
        clock.elapsed = DAY_SECONDS;
        assert!(!clock.is_day(), "night must start the instant DAY_SECONDS elapses");
        clock.elapsed = CYCLE_SECONDS - 0.001;
        assert!(!clock.is_day());
    }

    #[test]
    fn daylight_peaks_at_solar_noon_and_is_zero_all_night() {
        let noon = DayNightClock { elapsed: DAY_SECONDS / 2.0 };
        assert!((noon.daylight() - 1.0).abs() < 1e-5, "expected full daylight at the midpoint, got {}", noon.daylight());

        for frac in [0.0, 0.25, 0.5, 0.75, 0.999] {
            let night = DayNightClock { elapsed: DAY_SECONDS + NIGHT_SECONDS * frac };
            assert_eq!(night.daylight(), 0.0, "the moon must never brighten the world");
        }
    }

    #[test]
    fn sunrise_and_sunset_sit_exactly_on_the_east_west_horizon() {
        let radius = 100.0;

        let sunrise = DayNightClock { elapsed: 0.0 };
        let rise_pos = celestial_offset(sunrise.phase_angle(), radius);
        assert!((rise_pos - Vec3::new(radius, 0.0, 0.0)).length() < 1e-3, "sunrise should sit due east: {rise_pos:?}");

        // Just shy of DAY_SECONDS is still day (see
        // `day_lasts_exactly_twenty_minutes_and_night_ten`), with progress
        // essentially at 1 - i.e. the sun an instant from setting.
        let almost_sunset = DayNightClock { elapsed: DAY_SECONDS - 1e-3 };
        assert!(almost_sunset.is_day());
        let set_pos = celestial_offset(almost_sunset.phase_angle(), radius);
        assert!((set_pos - Vec3::new(-radius, 0.0, 0.0)).length() < 1e-3, "sunset should sit due west: {set_pos:?}");
    }

    #[test]
    fn zenith_sits_straight_up_with_no_east_west_drift() {
        let noon = DayNightClock { elapsed: DAY_SECONDS / 2.0 };
        let pos = celestial_offset(noon.phase_angle(), 100.0);
        assert!(pos.x.abs() < 1e-3, "zenith should have no east/west offset: {pos:?}");
        assert!((pos.y - 100.0).abs() < 1e-3, "zenith should be straight up: {pos:?}");
    }

    #[test]
    fn generated_sun_and_moon_textures_are_circular_and_distinct() {
        let sun = generate_sun_pixels(SKY_TEXTURE_SIZE);
        let moon = generate_moon_pixels(SKY_TEXTURE_SIZE);
        assert_eq!(sun.len(), SKY_TEXTURE_SIZE * SKY_TEXTURE_SIZE * 4);

        // A far corner (well outside any inscribed circle) must be transparent...
        let corner = 0; // pixel (0,0)
        assert_eq!(sun[corner * 4 + 3], 0, "sun's corner should be transparent");
        assert_eq!(moon[corner * 4 + 3], 0, "moon's corner should be transparent");

        // ...while dead center is fully opaque and the two textures differ
        // (a warm sun vs. a pale moon), so a custom-texture regression can't
        // silently swap them.
        let center = SKY_TEXTURE_SIZE / 2;
        let ci = (center * SKY_TEXTURE_SIZE + center) * 4;
        assert_eq!(sun[ci + 3], 255);
        assert_eq!(moon[ci + 3], 255);
        assert!(sun[ci] > sun[ci + 2] + 40, "the sun's center should read warm/gold, not neutral gray");
    }

    #[test]
    fn load_custom_sky_texture_returns_none_when_the_file_is_missing() {
        assert!(load_custom_sky_texture(Path::new("/nonexistent/dir"), "sun").is_none());
    }
}
