//! Day/night cycle: a real-time clock (20-minute days, 10-minute nights,
//! see [`DAY_SECONDS`]/[`NIGHT_SECONDS`]) driving a sun and a moon that rise
//! due east and set due west - this engine's established compass mapping
//! (`blocks.rs`'s face-order doc: +X east, -X west, -Z north, +Z south) -
//! arcing straight overhead through the zenith. Only one is ever up at a
//! time: the sun for the whole day phase, the moon for the whole night
//! phase, each completing its entire rise-to-set arc within its own phase's
//! duration.
//!
//! Both are flat, always-camera-facing quads (billboards) orbiting the
//! camera at a fixed radius - the same "attached to the sky, not the world"
//! trick real-time-strategy/voxel games have used forever, cheap because it
//! needs no new geometry per chunk and no dynamic light source at all.
//!
//! This is a fully unlit renderer (see `render.rs`'s module docs): there's
//! no real light to dim at night, so `update_sky` instead writes a single
//! global brightness multiplier (`render::ChunkMaterialParams::sky_light`)
//! into both chunk materials every frame, plus the sky/fog color - cheap
//! (two tiny uniform writes, no remeshing) despite touching the whole
//! world's apparent lighting at once.
//!
//! Sun/moon textures are procedurally generated by default (this module),
//! exactly like block textures (`atlas.rs`) - drop a `textures/sky/sun.png`
//! or `textures/sky/moon.png` to override one with real art instead; no
//! code changes, no recompile. Unlike the block atlas there's no shared
//! resolution or tile-packing to keep in sync, since each is one standalone
//! sprite - any square PNG is used at its own native size.
//!
//! The moon additionally cycles through 8 phases (new, waxing crescent,
//! first quarter, waxing gibbous, full, waning gibbous, last quarter,
//! waning crescent - see [`DayNightClock::moon_phase`]), one per full
//! day/night cycle, the same 8-phase-per-day convention Minecraft uses.
//! Each phase is a separately masked copy of the *same* base moon
//! texture (procedural or `moon.png`) - see [`moon_lit`] - rather than 8
//! independent images, so a custom `moon.png` override automatically gets
//! correct phase shapes with no extra files needed.
//!
//! Full moons also get an occasional special color, purely cosmetic for now
//! (no gameplay effect - see [`DayNightClock::moon_event`]): a **red moon**
//! twice a year, a **blue moon** once a year in [`Season::Summer`] (never
//! [`Season::Winter`]), and a **green moon** once a year in
//! [`Season::Autumn`] (never [`Season::Spring`]). Which month(s) each
//! lands on is re-rolled every year (seeded, not truly random - see
//! [`year_schedule`]), never the same month as another event that year and
//! never immediately next to one either - there's always at least one
//! plain-moon month of breathing room between any two specials, so a
//! blue/red/green chain can never land three months in a row. Each is a
//! plain color tint multiplied into the moon's existing texture
//! (`update_sky`), not a separate sprite.
//!
//! All of that - frequency, excluded seasons, whether an event even needs
//! a full moon, whether it needs a gap month - lives in one declarative
//! table ([`MOON_EVENTS`]), not per-event code: adding a fourth event, or
//! changing an existing one's frequency/season/gap rule, means editing
//! that table. [`Season`] itself is a pure calendar concept with no other
//! effect yet - it exists solely to make the excluded-season rules real
//! and checkable instead of a permanent no-op.
//!
//! The clock (and moon phase) persists per-world (`save::WorldData
//! ::time_of_day`/`::day_count`) so leaving and reloading resumes rather
//! than resetting to dawn/new-moon - the same
//! don't-silently-lose-continuous-state-on-reload lesson as fluids (see
//! CLAUDE.md).

use bevy::asset::embedded_asset;
use bevy::color::Mix;
use bevy::pbr::{MaterialPipeline, MaterialPipelineKey};
use bevy::prelude::*;
use bevy::render::mesh::{Indices, MeshVertexBufferLayoutRef, PrimitiveTopology};
use bevy::render::render_asset::RenderAssetUsages;
use bevy::render::render_resource::{
    AsBindGroup, Extent3d, RenderPipelineDescriptor, ShaderRef, ShaderType,
    SpecializedMeshPipelineError, TextureDimension, TextureFormat,
};
use std::f32::consts::{PI, TAU};
use std::path::{Path, PathBuf};

use crate::config::{WorldSettings, CHUNK_SIZE, SKY_COLOR};
use crate::noise::{hash_str, mulberry32};
use crate::player::Player;
use crate::render::{ChunkMaterial, ChunkMaterials};
use crate::state::AppState;

pub const DAY_SECONDS: f32 = 20.0 * 60.0;
pub const NIGHT_SECONDS: f32 = 10.0 * 60.0;
pub const CYCLE_SECONDS: f32 = DAY_SECONDS + NIGHT_SECONDS;

/// A "month" is defined to exactly match the moon's own 8-phase cycle, so
/// every month's full moon (`moon_phase() == 4`) always falls on the same
/// day-of-month. A "year" is a plain 12-month calendar, same ordering as
/// the real one (`Season::Spring` first) - see `DayNightClock::season`.
pub const DAYS_PER_MONTH: u32 = 8;
pub const MONTHS_PER_YEAR: u32 = 12;

/// One declarative special-moon-event rule. Adding a new event, or
/// changing an existing one's frequency/season/full-moon requirement,
/// means editing [`MOON_EVENTS`] below - never writing new scheduling
/// logic, since [`year_schedule`] and [`DayNightClock::moon_event`] are
/// both generic over this table.
struct MoonEventDef {
    event: MoonEvent,
    /// How many *different* months a year get this event - see
    /// `year_schedule` for how they're chosen (randomly, fresh every year,
    /// never the same month as another event that same year).
    per_year: u32,
    /// Seasons this event can never land in - `&[]` for no restriction.
    /// A comma-separated list, same as it reads: `&[Season::Winter]`,
    /// `&[Season::Winter, Season::Spring]`, etc.
    excluded_seasons: &'static [Season],
    /// If `true` (every event below sets it), the event only actually
    /// shows on its chosen month's full moon (`moon_phase() == 4`) - every
    /// other night that month is a plain moon. Exists as its own flag
    /// purely so a future event that isn't tied to the full moon can opt
    /// out (showing all month instead) without `moon_event` needing to
    /// special-case it by name.
    requires_full_moon: bool,
    /// If `true` (every event below sets it), this event's month(s) can
    /// never land immediately before or after *any* other special month
    /// already claimed that year (any event, not just its own kind) - so
    /// as long as every event in the table sets this, there's always at
    /// least one plain-moon month between any two specials, and a
    /// blue/red/green chain can never land three months in a row. Defaults
    /// to being opted into by every event here, but exists as its own flag
    /// so a future event that's fine appearing right next to another one
    /// can skip it - same reasoning as `requires_full_moon`.
    requires_gap_month: bool,
}

/// The whole special-moon-event schedule, in one place. Blue and green
/// each get one guaranteed-in-season month a year; red gets two completely
/// unrestricted months (so "once a month" from the original ask becomes
/// "twice a year" - see the module docs).
const MOON_EVENTS: &[MoonEventDef] = &[
    MoonEventDef {
        event: MoonEvent::Blue,
        per_year: 1,
        excluded_seasons: &[Season::Winter],
        requires_full_moon: true,
        requires_gap_month: true,
    },
    MoonEventDef {
        event: MoonEvent::Green,
        per_year: 1,
        excluded_seasons: &[Season::Spring],
        requires_full_moon: true,
        requires_gap_month: true,
    },
    MoonEventDef {
        event: MoonEvent::Red,
        per_year: 2,
        excluded_seasons: &[],
        requires_full_moon: true,
        requires_gap_month: true,
    },
];

/// Night's sky/fog color and the world's darkest brightness floor - never
/// fully black, matching the softly-lit look everything else in this
/// renderer already has.
const NIGHT_SKY: Color = Color::srgb(0.03, 0.04, 0.09);
const NIGHT_LIGHT: f32 = 0.22;
const DAY_LIGHT: f32 = 1.0;

/// The sun/moon's orbit radius and quad size, both expressed as a fraction
/// of the camera's far clip plane - sits comfortably inside it (so it's
/// never culled) regardless of `render_distance`.
const ORBIT_FRAC_OF_FAR: f32 = 0.85;
const SIZE_FRAC_OF_RADIUS: f32 = 0.12;

/// Native resolution of a procedurally generated sun/moon texture. A custom
/// `textures/sky/*.png` overrides this with its own size instead.
const SKY_TEXTURE_SIZE: usize = 64;

#[derive(Component)]
struct Sun;

#[derive(Component)]
struct Moon;

/// Real-time position in the day/night cycle. Advances every frame while in
/// a world (`advance_clock`) and is reset from - then kept in sync with -
/// the active world's save data (`world.rs`'s `enter_world`/`write_save`).
#[derive(Resource)]
pub struct DayNightClock {
    /// Seconds into the current `[0, CYCLE_SECONDS)` cycle. `0` is dawn:
    /// the sun exactly on the eastern horizon, about to rise.
    pub elapsed: f32,
    /// How many full day/night cycles have elapsed since the world began -
    /// increments the instant `elapsed` wraps back to `0` (`advance_clock`).
    /// Only ever consulted through [`Self::moon_phase`]; nothing else reads
    /// it directly.
    pub day_count: u32,
}

impl Default for DayNightClock {
    fn default() -> Self {
        Self { elapsed: 0.0, day_count: 0 }
    }
}

impl DayNightClock {
    pub fn is_day(&self) -> bool {
        self.elapsed < DAY_SECONDS
    }

    /// 0..1 progress through whichever of day/night is currently active -
    /// `0` right at rise, `1` right at set.
    fn phase_progress(&self) -> f32 {
        if self.is_day() {
            self.elapsed / DAY_SECONDS
        } else {
            (self.elapsed - DAY_SECONDS) / NIGHT_SECONDS
        }
    }

    /// The active body's angle above the eastern horizon: `0` at rise,
    /// `PI` at set, `PI/2` at zenith - see [`celestial_offset`].
    fn phase_angle(&self) -> f32 {
        self.phase_progress() * PI
    }

    /// `0` at rise/set, `1` at zenith. Doubles as both a fade-near-the-
    /// horizon factor and the world's daylight brightness (see
    /// [`Self::daylight`]) - a plain sine naturally eases both smoothly
    /// through sunrise/sunset with no separate interpolation needed.
    fn phase_height(&self) -> f32 {
        self.phase_angle().sin().max(0.0)
    }

    /// How daylit the world is right now: `0` at the depths of night up to
    /// `1` at high noon, driven entirely by the sun's height so sunrise and
    /// sunset ease naturally. Pinned to `0` for the whole night phase - the
    /// moon lights nothing, it just lets you see it's up.
    pub fn daylight(&self) -> f32 {
        if self.is_day() {
            self.phase_height()
        } else {
            0.0
        }
    }

    /// Which of the 8 moon phases is showing tonight: `0` = new, `2` =
    /// first quarter, `4` = full, `6` = last quarter, with a waxing
    /// crescent/gibbous at `1`/`3` and waning crescent/gibbous at `7`/`5` -
    /// advances by one every full day/night cycle (`advance_clock`), the
    /// same one-phase-per-day convention Minecraft uses. See [`moon_lit`]
    /// for how a phase index becomes a lit/dark shape.
    pub fn moon_phase(&self) -> u8 {
        (self.day_count % 8) as u8
    }

    /// How many full [`DAYS_PER_MONTH`]-day months have elapsed - a "month"
    /// is defined to exactly match the moon's own phase cycle, so a full
    /// moon (`moon_phase() == 4`) always lands in the middle of every month.
    fn month(&self) -> u32 {
        self.day_count / DAYS_PER_MONTH
    }

    /// `month()`, wrapped to a `[0, MONTHS_PER_YEAR)` position within the
    /// current year - what [`Self::season`] and [`Self::moon_event`] key off.
    fn month_of_year(&self) -> u32 {
        self.month() % MONTHS_PER_YEAR
    }

    /// The current calendar season - a pure calendar concept with no other
    /// gameplay effect yet (see the module docs): it exists solely so
    /// [`MoonEventDef::excluded_seasons`] is a real, checkable rule instead
    /// of a permanent no-op.
    pub fn season(&self) -> Season {
        season_of_month(self.month_of_year())
    }

    /// Tonight's special moon coloring, if any - see [`MOON_EVENTS`] for
    /// the full rules (frequency, excluded seasons, whether it needs a
    /// full moon). `world_seed` is `WorldSettings::seed`, threaded in
    /// rather than stored on the clock itself, since nothing else about
    /// the clock needs to know which world it belongs to. Purely cosmetic
    /// for now (see the module docs) - `update_sky` is the only consumer,
    /// tinting whichever phase material is currently shown.
    pub fn moon_event(&self, world_seed: u32) -> Option<MoonEvent> {
        let year = self.month() / MONTHS_PER_YEAR;
        let event = year_schedule(world_seed, year)[self.month_of_year() as usize]?;
        let def = MOON_EVENTS.iter().find(|d| d.event == event)?;
        if def.requires_full_moon && self.moon_phase() != 4 {
            return None;
        }
        Some(event)
    }
}

fn season_of_month(month_of_year: u32) -> Season {
    match month_of_year {
        0..=2 => Season::Spring,
        3..=5 => Season::Summer,
        6..=8 => Season::Autumn,
        _ => Season::Winter, // 9..=11
    }
}

/// True if `month` sits immediately before or after a month that already
/// has an event this year, *or* is month `0` and `previous_december_claimed`.
/// That second case is the one piece of cross-year information
/// [`year_schedule`] threads in so the gap rule holds across a year
/// boundary too (no claimed December immediately followed by a claimed
/// January), not just within one year.
fn touches_a_claimed_month(
    month: u32,
    schedule: &[Option<MoonEvent>; MONTHS_PER_YEAR as usize],
    previous_december_claimed: bool,
) -> bool {
    let before_claimed = if month == 0 {
        previous_december_claimed
    } else {
        schedule[month as usize - 1].is_some()
    };
    before_claimed || (month + 1 < MONTHS_PER_YEAR && schedule[month as usize + 1].is_some())
}

/// Deterministically (but pseudo-randomly, re-rolled fresh every year)
/// assigns one year's [`MOON_EVENTS`] occurrences to specific months -
/// `[i]` is which event (if any) month `i` hosts. Seeded from the world's
/// seed plus the year number, so it's reproducible for a given world and
/// year (a reload must show the same schedule) but differs world to world
/// and year to year - the same seeded-not-truly-random determinism every
/// other procedural piece of this engine (terrain, block texture jitter)
/// already follows.
///
/// Events are drawn in [`MOON_EVENTS`]'s table order, each occurrence
/// picking fresh from whatever's currently eligible: not yet claimed this
/// year, not in one of the event's own excluded seasons, and (if
/// `requires_gap_month`) not touching an already-claimed month, including
/// the previous year's December via `previous_december_claimed` -
/// recomputed after every single pick, not just once per event, so an
/// event drawing more than one occurrence (red draws two) can't land its
/// own two months next to each other either. Table order acts as a
/// priority (earlier entries get first pick of any months two entries
/// could both use - e.g. blue's non-winter pool and green's non-spring
/// pool genuinely overlap in summer/autumn), but claiming as each month is
/// picked is what actually guarantees no two events ever collide or end up
/// adjacent, regardless of how much their pools overlap. If an event's
/// eligible pool ever runs dry before `per_year` is satisfied (possible in
/// principle with a much more restrictive custom table than the one
/// below), it simply gets fewer occurrences that year rather than panicking.
fn year_schedule_one_year(
    world_seed: u32,
    year: u32,
    previous_december_claimed: bool,
) -> [Option<MoonEvent>; MONTHS_PER_YEAR as usize] {
    let mut schedule = [None; MONTHS_PER_YEAR as usize];
    let base = hash_str(&format!("moon-events-{world_seed}-{year}"));
    for (i, def) in MOON_EVENTS.iter().enumerate() {
        // A large prime offset per event index gives each its own
        // independent pseudo-random stream from the same year's base seed.
        let mut rng = mulberry32(base.wrapping_add(i as u32 * 104_729));
        for _ in 0..def.per_year {
            let pool: Vec<u32> = (0..MONTHS_PER_YEAR)
                .filter(|&m| {
                    schedule[m as usize].is_none()
                        && !def.excluded_seasons.contains(&season_of_month(m))
                        && (!def.requires_gap_month
                            || !touches_a_claimed_month(m, &schedule, previous_december_claimed))
                })
                .collect();
            if pool.is_empty() {
                break;
            }
            let idx = ((rng() * pool.len() as f32) as usize).min(pool.len() - 1);
            schedule[pool[idx] as usize] = Some(def.event);
        }
    }
    schedule
}

/// [`year_schedule_one_year`], but carries the gap rule across year
/// boundaries too: a claimed December must block the following January
/// exactly as it would block any other adjacent month, which needs to know
/// whether *last* year's December was claimed - which itself depends on
/// the year before that, all the way back to year `0`. Walking forward
/// from year `0` and keeping only that one rolling fact (never the full
/// history of every prior year) keeps this cheap regardless of how large
/// `year` gets over a long-lived save: `O(year)` tiny 12-month passes, not
/// `O(year)` worth of state kept around. `update_sky` calls this fresh
/// every frame like everything else in this module - even a save many
/// real-world years old is nowhere near enough played time (at 30 minutes
/// per in-game day, one in-game year is 48 real hours) to make that loop
/// noticeable.
fn year_schedule(world_seed: u32, target_year: u32) -> [Option<MoonEvent>; MONTHS_PER_YEAR as usize] {
    let mut schedule = [None; MONTHS_PER_YEAR as usize];
    let mut previous_december_claimed = false;
    for year in 0..=target_year {
        schedule = year_schedule_one_year(world_seed, year, previous_december_claimed);
        previous_december_claimed = schedule[MONTHS_PER_YEAR as usize - 1].is_some();
    }
    schedule
}

/// A pure calendar concept (see [`DayNightClock::season`]'s doc comment) -
/// no other system reads this yet.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Season {
    Spring,
    Summer,
    Autumn,
    Winter,
}

/// A special full-moon coloring - see [`DayNightClock::moon_event`] and
/// [`MOON_EVENTS`] for the actual rules; this enum is just the set of
/// colors that exist.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum MoonEvent {
    Red,
    Blue,
    Green,
}

/// The tint multiplied into the moon's texture color for a [`MoonEvent`] -
/// `None` (an ordinary full moon night never reached via [`MoonEvent`]
/// itself, but also what every *non*-full-moon night uses) is a no-op white.
fn moon_event_tint(event: Option<MoonEvent>) -> LinearRgba {
    match event {
        None => LinearRgba::WHITE,
        Some(MoonEvent::Red) => LinearRgba::new(1.0, 0.35, 0.3, 1.0),
        Some(MoonEvent::Blue) => LinearRgba::new(0.4, 0.55, 1.0, 1.0),
        Some(MoonEvent::Green) => LinearRgba::new(0.45, 0.95, 0.5, 1.0),
    }
}

/// East-to-west arc offset from the camera for `angle` (`0` = due east
/// horizon, `PI/2` = zenith, `PI` = due west horizon) at `radius` - a plain
/// overhead great circle, ignoring latitude/season for simplicity (see the
/// module docs for the compass mapping this relies on).
fn celestial_offset(angle: f32, radius: f32) -> Vec3 {
    Vec3::new(angle.cos() * radius, angle.sin() * radius, 0.0)
}

#[derive(Clone, ShaderType)]
#[allow(dead_code)] // the ShaderType derive generates per-field check fns
struct CelestialParams {
    tint: LinearRgba,
}

#[derive(Asset, TypePath, AsBindGroup, Clone)]
struct CelestialMaterial {
    #[texture(0)]
    #[sampler(1)]
    texture: Handle<Image>,
    #[uniform(2)]
    params: CelestialParams,
}

impl Material for CelestialMaterial {
    fn fragment_shader() -> ShaderRef {
        "embedded://craftmjne/celestial.wgsl".into()
    }

    fn alpha_mode(&self) -> AlphaMode {
        AlphaMode::Blend
    }

    fn specialize(
        _pipeline: &MaterialPipeline<Self>,
        descriptor: &mut RenderPipelineDescriptor,
        _layout: &MeshVertexBufferLayoutRef,
        _key: MaterialPipelineKey<Self>,
    ) -> Result<(), SpecializedMeshPipelineError> {
        // A billboard has no "back" worth culling - it's always turned to
        // face the camera, but cheaply skipping the exact winding-order
        // math to guarantee that is one less thing to get subtly wrong.
        descriptor.primitive.cull_mode = None;
        Ok(())
    }
}

#[derive(Resource)]
struct SkyMaterials {
    sun: Handle<CelestialMaterial>,
    /// One material per moon phase (index = `DayNightClock::moon_phase()`,
    /// always length 8) - a separate material per phase rather than one
    /// shared material with a swapped texture handle, so the moon's
    /// `MeshMaterial3d` component can just be reassigned wholesale when the
    /// phase changes (see `update_sky`), no per-frame `Assets<Image>` churn.
    moon_phases: Vec<Handle<CelestialMaterial>>,
}

/// A unit quad in the XY plane, centered on the origin - scaled to its
/// final size per-frame via `Transform::scale` (see `update_sky`), since
/// that size depends on `WorldSettings::render_distance`, which can change
/// after this mesh is built. Carries a uniform white vertex color purely to
/// match `render::bucket_to_mesh`'s proven-working attribute set (position +
/// UV + color, no normals) rather than risk an untested minimal layout.
fn quad_mesh() -> Mesh {
    let mut mesh = Mesh::new(PrimitiveTopology::TriangleList, RenderAssetUsages::default());
    mesh.insert_attribute(
        Mesh::ATTRIBUTE_POSITION,
        vec![[-0.5, -0.5, 0.0], [0.5, -0.5, 0.0], [0.5, 0.5, 0.0], [-0.5, 0.5, 0.0]],
    );
    mesh.insert_attribute(
        Mesh::ATTRIBUTE_UV_0,
        vec![[0.0, 1.0], [1.0, 1.0], [1.0, 0.0], [0.0, 0.0]],
    );
    mesh.insert_attribute(
        Mesh::ATTRIBUTE_COLOR,
        vec![[1.0, 1.0, 1.0, 1.0]; 4],
    );
    mesh.insert_indices(Indices::U32(vec![0, 1, 2, 0, 2, 3]));
    mesh
}

/// Where to look for `textures/sky/`: next to the running executable first
/// (how an installed/shipped build finds files shipped next to it), falling
/// back to the current working directory (how `cargo run`/tests find one at
/// the repo root). Mirrors `atlas::find_textures_dir`/`blocks::find_blocks_dir`
/// exactly.
fn find_sky_dir() -> PathBuf {
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let candidate = dir.join("textures").join("sky");
            if candidate.is_dir() {
                return candidate;
            }
        }
    }
    PathBuf::from("textures").join("sky")
}

/// Loads `<dir>/<name>.png` if present, decoded to raw RGBA8 plus its
/// (square) size - `None` if the file just isn't there, so the procedural
/// texture is used instead. Panics on a malformed file (not square,
/// unreadable/corrupt), matching `atlas::load_custom_tile`'s "a broken file
/// is a mistake worth surfacing loudly, not papering over" precedent.
fn load_custom_sky_texture(dir: &Path, name: &str) -> Option<(Vec<u8>, u32)> {
    let path = dir.join(format!("{name}.png"));
    if !path.is_file() {
        return None;
    }
    let img = image::open(&path)
        .unwrap_or_else(|err| panic!("failed to read texture {path:?}: {err}"))
        .into_rgba8();
    let (w, h) = (img.width(), img.height());
    if w != h {
        panic!("texture {path:?} is {w}x{h}, but sun/moon textures must be square");
    }
    Some((img.into_raw(), w))
}

/// A checkered-disc "moon crater" placement helper: `n` deterministic
/// (x, y, radius) blobs scattered within `radius * 0.65` of center, seeded
/// from `rng` so a fresh call each startup is reproducible run-to-run.
fn scatter_craters(rng: &mut dyn FnMut() -> f32, n: usize, center: f32, radius: f32) -> Vec<(f32, f32, f32)> {
    (0..n)
        .map(|_| {
            let a = rng() * TAU;
            let d = rng() * radius * 0.65;
            let cr = radius * (0.12 + rng() * 0.1);
            (center + a.cos() * d, center + a.sin() * d, cr)
        })
        .collect()
}

/// A warm gold disc, brightest at the center and deepening toward a soft
/// orange rim, fully transparent outside its radius.
fn generate_sun_pixels(size: usize) -> Vec<u8> {
    let mut rng = mulberry32(hash_str("sun"));
    let mut pixels = vec![0u8; size * size * 4];
    let center = (size as f32 - 1.0) * 0.5;
    let radius = size as f32 * 0.48;
    for y in 0..size {
        for x in 0..size {
            let dx = x as f32 - center;
            let dy = y as f32 - center;
            let dist = (dx * dx + dy * dy).sqrt();
            if dist > radius {
                continue; // stays fully transparent - the buffer starts zeroed
            }
            let t = (dist / radius).clamp(0.0, 1.0);
            let jitter = (rng() - 0.5) * 18.0;
            let r = (255.0 - t * 25.0 + jitter).clamp(0.0, 255.0);
            let g = (214.0 - t * 60.0 + jitter).clamp(0.0, 255.0);
            let b = (110.0 - t * 70.0 + jitter * 0.5).clamp(0.0, 255.0);
            let i = (y * size + x) * 4;
            pixels[i] = r as u8;
            pixels[i + 1] = g as u8;
            pixels[i + 2] = b as u8;
            pixels[i + 3] = 255;
        }
    }
    pixels
}

/// A pale gray-white disc with a handful of darker craters, fully
/// transparent outside its radius.
fn generate_moon_pixels(size: usize) -> Vec<u8> {
    let mut rng = mulberry32(hash_str("moon"));
    let mut pixels = vec![0u8; size * size * 4];
    let center = (size as f32 - 1.0) * 0.5;
    let radius = size as f32 * 0.48;
    let craters = scatter_craters(&mut rng, 6, center, radius);
    for y in 0..size {
        for x in 0..size {
            let dx = x as f32 - center;
            let dy = y as f32 - center;
            let dist = (dx * dx + dy * dy).sqrt();
            if dist > radius {
                continue;
            }
            let jitter = (rng() - 0.5) * 10.0;
            let mut c = 222.0 + jitter;
            for &(cx, cy, cr) in &craters {
                let cd = ((x as f32 - cx).powi(2) + (y as f32 - cy).powi(2)).sqrt();
                if cd < cr {
                    c -= (1.0 - cd / cr) * 45.0;
                }
            }
            let c = c.clamp(60.0, 255.0);
            let i = (y * size + x) * 4;
            pixels[i] = c as u8;
            pixels[i + 1] = c as u8;
            pixels[i + 2] = (c * 0.97) as u8;
            pixels[i + 3] = 255;
        }
    }
    pixels
}

fn sky_texture(dir: &Path, name: &str, procedural: fn(usize) -> Vec<u8>) -> (Vec<u8>, u32) {
    load_custom_sky_texture(dir, name)
        .unwrap_or_else(|| (procedural(SKY_TEXTURE_SIZE), SKY_TEXTURE_SIZE as u32))
}

/// Whether a point `(nx, ny)` on the moon's disc - normalized so the disc
/// is the unit circle (`nx² + ny² <= 1`) - falls on the illuminated side
/// for `phase` (`0..8`, see [`DayNightClock::moon_phase`]).
///
/// The boundary is a proper elliptical terminator, not a flat chord: at a
/// given height `ny`, the disc's edge sits at `sqrt(1 - ny²)`, and the lit
/// boundary at that height is that same edge scaled by `cos(theta)` - which
/// collapses to a straight vertical line exactly at the quarter phases
/// (astronomically correct: cos is 0 there) and bows into a proper curved
/// crescent/gibbous everywhere else. `phase < 4` (new -> full, waxing) is
/// lit on the `+x` (east/right) side growing inward from nothing; `phase >
/// 4` (full -> new, waning) is lit on the `-x` (west/left) side shrinking
/// the same way - `4` and `0` are special-cased rather than trusting
/// `cos(PI)`/`cos(0)` to land on an exact float boundary.
fn moon_lit(nx: f32, ny: f32, phase: u8) -> bool {
    match phase {
        0 => false,
        4 => true,
        _ => {
            let theta = phase as f32 * PI / 4.0;
            let edge = (1.0 - ny * ny).max(0.0).sqrt();
            if phase < 4 {
                nx >= theta.cos() * edge
            } else {
                nx <= -theta.cos() * edge
            }
        }
    }
}

/// Masks `pixels` (a `size`x`size` RGBA8 buffer, square) down to just the
/// portion lit for `phase`, forcing everything else fully transparent -
/// applied to whichever base moon texture is in play (procedural or a
/// custom `moon.png`), so a single source image yields all 8 phases with no
/// extra art required.
fn mask_moon_phase(pixels: &[u8], size: u32, phase: u8) -> Vec<u8> {
    let size = size as usize;
    let mut out = pixels.to_vec();
    let center = (size as f32 - 1.0) * 0.5;
    let half = size as f32 * 0.5;
    for y in 0..size {
        for x in 0..size {
            let i = (y * size + x) * 4;
            if out[i + 3] == 0 {
                continue; // already transparent outside the base disc
            }
            let nx = (x as f32 - center) / half;
            let ny = (y as f32 - center) / half;
            if !moon_lit(nx, ny, phase) {
                out[i + 3] = 0;
            }
        }
    }
    out
}

fn upload_sky_image(pixels: Vec<u8>, size: u32) -> Image {
    Image::new(
        Extent3d { width: size, height: size, depth_or_array_layers: 1 },
        TextureDimension::D2,
        pixels,
        TextureFormat::Rgba8UnormSrgb,
        RenderAssetUsages::default(),
    )
    // Deliberately not nearest-sampled (unlike the block atlas): these are
    // smooth gradient discs, not pixel art, so the default linear filtering
    // is what makes the edge and shading actually look round.
}

/// Startup: generates (or loads custom) sun/moon textures, and spawns both
/// as hidden billboards - `update_sky` takes over their position, facing,
/// and visibility every frame once a world's loaded.
fn spawn_sky(
    mut commands: Commands,
    mut images: ResMut<Assets<Image>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<CelestialMaterial>>,
) {
    let dir = find_sky_dir();
    let (sun_pixels, sun_size) = sky_texture(&dir, "sun", generate_sun_pixels);
    let (moon_pixels, moon_size) = sky_texture(&dir, "moon", generate_moon_pixels);

    let sun_handle = images.add(upload_sky_image(sun_pixels, sun_size));
    let mesh = meshes.add(quad_mesh());

    let sun = materials.add(CelestialMaterial {
        texture: sun_handle,
        params: CelestialParams { tint: LinearRgba::WHITE },
    });
    let moon_phases: Vec<Handle<CelestialMaterial>> = (0..8u8)
        .map(|phase| {
            let masked = mask_moon_phase(&moon_pixels, moon_size, phase);
            let handle = images.add(upload_sky_image(masked, moon_size));
            materials.add(CelestialMaterial {
                texture: handle,
                params: CelestialParams { tint: LinearRgba::WHITE },
            })
        })
        .collect();

    commands.spawn((Sun, Mesh3d(mesh.clone()), MeshMaterial3d(sun.clone()), Visibility::Hidden));
    commands.spawn((Moon, Mesh3d(mesh), MeshMaterial3d(moon_phases[0].clone()), Visibility::Hidden));
    commands.insert_resource(SkyMaterials { sun, moon_phases });
}

/// Advances `elapsed` by `delta` seconds, wrapping into `[0, CYCLE_SECONDS)`
/// and bumping `day_count` exactly when that wrap happens - pure logic
/// pulled out of `advance_clock` so it's directly testable without needing
/// a full Bevy `Time`/`ResMut` system context.
fn advance(elapsed: f32, day_count: u32, delta: f32) -> (f32, u32) {
    let next = (elapsed + delta).rem_euclid(CYCLE_SECONDS);
    let day_count = if next < elapsed { day_count.wrapping_add(1) } else { day_count };
    (next, day_count)
}

fn advance_clock(time: Res<Time>, mut clock: ResMut<DayNightClock>) {
    let (elapsed, day_count) = advance(clock.elapsed, clock.day_count, time.delta_secs());
    clock.elapsed = elapsed;
    clock.day_count = day_count;
}

/// Every frame: positions/orients whichever of the sun or moon is
/// currently up (orbiting the camera, always facing it), fades it in/out
/// near the horizon, and writes the day/night-driven sky color + chunk
/// brightness (`render::ChunkMaterialParams::sky_light`) - see the module
/// docs for why a single global multiplier is this renderer's stand-in for
/// a real light source.
#[allow(clippy::too_many_arguments)]
fn update_sky(
    clock: Res<DayNightClock>,
    settings: Res<WorldSettings>,
    sky_materials: Res<SkyMaterials>,
    chunk_materials: Res<ChunkMaterials>,
    camera: Query<&Transform, (With<Player>, Without<Sun>, Without<Moon>)>,
    mut sun: Query<(&mut Transform, &mut Visibility), (With<Sun>, Without<Moon>, Without<Player>)>,
    mut moon: Query<
        (&mut Transform, &mut Visibility, &mut MeshMaterial3d<CelestialMaterial>),
        (With<Moon>, Without<Sun>, Without<Player>),
    >,
    mut clear_color: ResMut<ClearColor>,
    mut celestial_assets: ResMut<Assets<CelestialMaterial>>,
    mut chunk_assets: ResMut<Assets<ChunkMaterial>>,
) {
    let Ok(camera_tf) = camera.single() else { return };
    let Ok((mut sun_tf, mut sun_vis)) = sun.single_mut() else { return };
    let Ok((mut moon_tf, mut moon_vis, mut moon_material)) = moon.single_mut() else { return };
    let moon_phase_material = &sky_materials.moon_phases[clock.moon_phase() as usize];
    // The moon phase only actually changes once every ~30 minutes, but
    // reassigning every frame is cheap for one quad and matches how the
    // Transform/Visibility right below it are already handled - simpler
    // than change-detecting a value that barely ever changes.
    *moon_material = MeshMaterial3d(moon_phase_material.clone());

    let far = (settings.render_distance * CHUNK_SIZE) as f32 * 2.0;
    let radius = far * ORBIT_FRAC_OF_FAR;
    let size = radius * SIZE_FRAC_OF_RADIUS;

    let offset = celestial_offset(clock.phase_angle(), radius);
    let pos = camera_tf.translation + offset;
    // Both bodies are radially symmetric discs, so any roll around the
    // view axis looks identical - `from_rotation_arc` (unlike
    // `Transform::looking_at`) needs no separate up vector and so has no
    // degenerate case at the zenith, where the look direction is exactly
    // parallel to world-up.
    let facing = Quat::from_rotation_arc(Vec3::NEG_Z, (camera_tf.translation - pos).normalize());
    // Never fully transparent while up - fades toward the horizon instead
    // of an abrupt pop into/out of existence at the exact rise/set instant.
    let fade = clock.phase_height() * 0.7 + 0.3;

    let is_day = clock.is_day();

    *sun_vis = if is_day { Visibility::Visible } else { Visibility::Hidden };
    if is_day {
        sun_tf.translation = pos;
        sun_tf.scale = Vec3::splat(size);
        sun_tf.rotation = facing;
    }
    if let Some(mat) = celestial_assets.get_mut(&sky_materials.sun) {
        mat.params.tint.alpha = if is_day { fade } else { 0.0 };
    }

    *moon_vis = if is_day { Visibility::Hidden } else { Visibility::Visible };
    if !is_day {
        moon_tf.translation = pos;
        moon_tf.scale = Vec3::splat(size);
        moon_tf.rotation = facing;
    }
    if let Some(mat) = celestial_assets.get_mut(moon_phase_material) {
        let color = moon_event_tint(clock.moon_event(settings.seed));
        let alpha = if !is_day { fade } else { 0.0 };
        mat.params.tint = LinearRgba::new(color.red, color.green, color.blue, alpha);
    }

    let daylight = clock.daylight();
    let sky_color = NIGHT_SKY.mix(&SKY_COLOR, daylight);
    clear_color.0 = sky_color;
    let fog_color = LinearRgba::from(sky_color);
    let sky_light = NIGHT_LIGHT + (DAY_LIGHT - NIGHT_LIGHT) * daylight;
    for handle in [&chunk_materials.solid, &chunk_materials.water] {
        if let Some(mat) = chunk_assets.get_mut(handle) {
            mat.params.fog_color = fog_color;
            mat.params.sky_light = sky_light;
        }
    }
}

pub struct SkyPlugin;

impl Plugin for SkyPlugin {
    fn build(&self, app: &mut App) {
        embedded_asset!(app, "celestial.wgsl");
        app.add_plugins(MaterialPlugin::<CelestialMaterial>::default())
            .init_resource::<DayNightClock>()
            .add_systems(Startup, spawn_sky)
            .add_systems(
                Update,
                (advance_clock, update_sky)
                    .chain()
                    .run_if(in_state(AppState::InGame)),
            );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_fresh_clock_starts_at_dawn() {
        let clock = DayNightClock::default();
        assert!(clock.is_day());
        assert_eq!(clock.phase_progress(), 0.0);
        assert_eq!(clock.daylight(), 0.0); // sun is exactly on the horizon
        assert_eq!(clock.moon_phase(), 0); // new moon
    }

    #[test]
    fn moon_phase_advances_once_per_day_count_and_wraps_every_eight() {
        for (day_count, expected) in [(0, 0), (1, 1), (4, 4), (7, 7), (8, 0), (9, 1), (100, 4)] {
            let clock = DayNightClock { day_count, ..Default::default() };
            assert_eq!(clock.moon_phase(), expected, "day_count {day_count}");
        }
    }

    #[test]
    fn month_of_year_wraps_every_twelve_months() {
        for (month, expected) in [(0, 0), (1, 1), (11, 11), (12, 0), (13, 1), (24, 0), (100, 4)] {
            let clock = DayNightClock { day_count: month * DAYS_PER_MONTH, ..Default::default() };
            assert_eq!(clock.month_of_year(), expected, "month {month}");
        }
    }

    #[test]
    fn season_follows_the_real_spring_summer_autumn_winter_ordering() {
        let season_of = |month_of_year: u32| {
            DayNightClock { day_count: month_of_year * DAYS_PER_MONTH, ..Default::default() }.season()
        };
        for m in 0..=2 {
            assert_eq!(season_of(m), Season::Spring, "month {m}");
        }
        for m in 3..=5 {
            assert_eq!(season_of(m), Season::Summer, "month {m}");
        }
        for m in 6..=8 {
            assert_eq!(season_of(m), Season::Autumn, "month {m}");
        }
        for m in 9..=11 {
            assert_eq!(season_of(m), Season::Winter, "month {m}");
        }
        // And it must wrap back to spring for the next year, not keep
        // counting new seasons forever.
        assert_eq!(season_of(12), Season::Spring);
    }

    #[test]
    fn a_non_full_moon_never_has_a_special_event_regardless_of_month() {
        // Try every month (some of which will be this seed/year's actual
        // blue/green/red months) at every non-full phase - even a
        // "special" month must stay a plain moon on every night that
        // isn't its one full moon.
        for month in 0..MONTHS_PER_YEAR {
            for phase in [0u8, 1, 2, 3, 5, 6, 7] {
                let day_count = month * DAYS_PER_MONTH + phase as u32;
                let clock = DayNightClock { day_count, ..Default::default() };
                assert_eq!(clock.moon_phase(), phase);
                assert_eq!(clock.moon_event(42), None, "month {month} phase {phase} must never be a special event");
            }
        }
    }

    /// Exercises `year_schedule` directly (rather than `moon_event`, which
    /// only ever returns `Some` on the exact full-moon night) so the whole
    /// year's assignment can be checked at once: exactly 2 red + 1 blue +
    /// 1 green, no month double-booked, and the season exclusions hold -
    /// across a spread of seeds/years, since the schedule is now random
    /// per (seed, year) rather than a fixed month.
    #[test]
    fn year_schedule_always_places_the_right_counts_with_no_overlap_or_excluded_season() {
        for world_seed in [0u32, 1, 42, 12345, u32::MAX] {
            for year in 0u32..5 {
                let schedule = year_schedule(world_seed, year);

                let count = |event: MoonEvent| schedule.iter().filter(|&&m| m == Some(event)).count();
                assert_eq!(count(MoonEvent::Red), 2, "seed {world_seed} year {year}: expected 2 red moons");
                assert_eq!(count(MoonEvent::Blue), 1, "seed {world_seed} year {year}: expected 1 blue moon");
                assert_eq!(count(MoonEvent::Green), 1, "seed {world_seed} year {year}: expected 1 green moon");
                assert_eq!(
                    schedule.iter().filter(|m| m.is_some()).count(),
                    4,
                    "seed {world_seed} year {year}: no month should host two events"
                );

                for (month, event) in schedule.iter().enumerate() {
                    let season = season_of_month(month as u32);
                    match event {
                        Some(MoonEvent::Blue) => {
                            assert_ne!(season, Season::Winter, "seed {world_seed} year {year}: blue moon in winter")
                        }
                        Some(MoonEvent::Green) => {
                            assert_ne!(season, Season::Spring, "seed {world_seed} year {year}: green moon in spring")
                        }
                        _ => {}
                    }
                }
            }
        }
    }

    /// Every event in `MOON_EVENTS` sets `requires_gap_month: true`, so no
    /// two special months should ever be adjacent - regardless of which
    /// events they are (a blue moon right after a red moon is just as
    /// disallowed as two reds in a row). Swept over many more seeds than
    /// the other schedule tests since this is exactly the kind of
    /// off-by-one a single hand-picked example could miss.
    #[test]
    fn no_two_special_months_are_ever_adjacent() {
        for world_seed in 0u32..500 {
            for year in 0u32..5 {
                let schedule = year_schedule(world_seed, year);
                for month in 0..MONTHS_PER_YEAR as usize {
                    if schedule[month].is_some() && month + 1 < schedule.len() {
                        assert!(
                            schedule[month + 1].is_none(),
                            "seed {world_seed} year {year}: months {month} and {} are both special",
                            month + 1
                        );
                    }
                }
            }
        }
    }

    /// The exact scenario this was asked for: a claimed December must
    /// never be immediately followed by a claimed January the next year -
    /// checked across many consecutive year pairs, not just within one
    /// year's own boundaries (`no_two_special_months_are_ever_adjacent`
    /// above only ever looks inside a single year's 12 months).
    #[test]
    fn no_special_lands_in_january_right_after_a_claimed_december() {
        for world_seed in 0u32..500 {
            for year in 1u32..8 {
                let previous_december = year_schedule(world_seed, year - 1)[MONTHS_PER_YEAR as usize - 1];
                let this_january = year_schedule(world_seed, year)[0];
                if previous_december.is_some() {
                    assert!(
                        this_january.is_none(),
                        "seed {world_seed}: December of year {} ({previous_december:?}) is immediately \
                         followed by a claimed January of year {year} ({this_january:?})",
                        year - 1
                    );
                }
            }
        }
    }

    #[test]
    fn year_schedule_is_deterministic_for_the_same_seed_and_year() {
        assert_eq!(year_schedule(7, 3), year_schedule(7, 3));
    }

    #[test]
    fn a_full_moon_shows_whatever_its_scheduled_month_says() {
        let world_seed = 999;
        let schedule = year_schedule(world_seed, 0);
        for (month, expected) in schedule.iter().enumerate() {
            let clock = DayNightClock { day_count: month as u32 * DAYS_PER_MONTH + 4, ..Default::default() };
            assert_eq!(clock.moon_event(world_seed), *expected, "month {month}");
        }
    }

    #[test]
    fn moon_event_tint_is_a_plain_white_no_op_for_an_ordinary_moon() {
        assert_eq!(moon_event_tint(None), LinearRgba::WHITE);
    }

    #[test]
    fn each_moon_event_gets_a_visually_distinct_tint() {
        let red = moon_event_tint(Some(MoonEvent::Red));
        let blue = moon_event_tint(Some(MoonEvent::Blue));
        let green = moon_event_tint(Some(MoonEvent::Green));
        assert!(red.red > red.green && red.red > red.blue, "red moon should read red");
        assert!(blue.blue > blue.red && blue.blue > blue.green, "blue moon should read blue");
        assert!(green.green > green.red && green.green > green.blue, "green moon should read green");
    }

    #[test]
    fn advance_bumps_day_count_exactly_when_the_cycle_wraps() {
        let (elapsed, day_count) = advance(CYCLE_SECONDS - 1.0, 3, 0.5);
        assert!(elapsed > CYCLE_SECONDS - 1.0, "not wrapping yet");
        assert_eq!(day_count, 3, "must not bump before the wrap actually happens");

        let (elapsed, day_count) = advance(elapsed, day_count, 1.0);
        assert!(elapsed < 1.0, "this step should have wrapped");
        assert_eq!(day_count, 4);
    }

    #[test]
    fn advance_never_bumps_day_count_mid_cycle() {
        let (_, day_count) = advance(0.0, 7, DAY_SECONDS);
        assert_eq!(day_count, 7, "reaching night from dawn is not a wrap");
    }

    #[test]
    fn the_clock_stays_within_one_cycle_and_wraps_smoothly() {
        let mut clock = DayNightClock { elapsed: CYCLE_SECONDS - 1.0, ..Default::default() };
        clock.elapsed = (clock.elapsed + 2.0).rem_euclid(CYCLE_SECONDS);
        assert!((clock.elapsed - 1.0).abs() < 1e-4, "expected to wrap just past 0, got {}", clock.elapsed);
    }

    #[test]
    fn day_lasts_exactly_twenty_minutes_and_night_ten() {
        assert_eq!(DAY_SECONDS, 1200.0);
        assert_eq!(NIGHT_SECONDS, 600.0);
        let mut clock = DayNightClock { elapsed: DAY_SECONDS - 0.001, ..Default::default() };
        assert!(clock.is_day());
        clock.elapsed = DAY_SECONDS;
        assert!(!clock.is_day(), "night must start the instant DAY_SECONDS elapses");
        clock.elapsed = CYCLE_SECONDS - 0.001;
        assert!(!clock.is_day());
    }

    #[test]
    fn daylight_peaks_at_solar_noon_and_is_zero_all_night() {
        let noon = DayNightClock { elapsed: DAY_SECONDS / 2.0, ..Default::default() };
        assert!((noon.daylight() - 1.0).abs() < 1e-5, "expected full daylight at the midpoint, got {}", noon.daylight());

        for frac in [0.0, 0.25, 0.5, 0.75, 0.999] {
            let night = DayNightClock { elapsed: DAY_SECONDS + NIGHT_SECONDS * frac, ..Default::default() };
            assert_eq!(night.daylight(), 0.0, "the moon must never brighten the world");
        }
    }

    #[test]
    fn sunrise_and_sunset_sit_exactly_on_the_east_west_horizon() {
        let radius = 100.0;

        let sunrise = DayNightClock { elapsed: 0.0, ..Default::default() };
        let rise_pos = celestial_offset(sunrise.phase_angle(), radius);
        assert!((rise_pos - Vec3::new(radius, 0.0, 0.0)).length() < 1e-3, "sunrise should sit due east: {rise_pos:?}");

        // Just shy of DAY_SECONDS is still day (see
        // `day_lasts_exactly_twenty_minutes_and_night_ten`), with progress
        // essentially at 1 - i.e. the sun an instant from setting.
        let almost_sunset = DayNightClock { elapsed: DAY_SECONDS - 1e-3, ..Default::default() };
        assert!(almost_sunset.is_day());
        let set_pos = celestial_offset(almost_sunset.phase_angle(), radius);
        assert!((set_pos - Vec3::new(-radius, 0.0, 0.0)).length() < 1e-3, "sunset should sit due west: {set_pos:?}");
    }

    #[test]
    fn zenith_sits_straight_up_with_no_east_west_drift() {
        let noon = DayNightClock { elapsed: DAY_SECONDS / 2.0, ..Default::default() };
        let pos = celestial_offset(noon.phase_angle(), 100.0);
        assert!(pos.x.abs() < 1e-3, "zenith should have no east/west offset: {pos:?}");
        assert!((pos.y - 100.0).abs() < 1e-3, "zenith should be straight up: {pos:?}");
    }

    #[test]
    fn generated_sun_and_moon_textures_are_circular_and_distinct() {
        let sun = generate_sun_pixels(SKY_TEXTURE_SIZE);
        let moon = generate_moon_pixels(SKY_TEXTURE_SIZE);
        assert_eq!(sun.len(), SKY_TEXTURE_SIZE * SKY_TEXTURE_SIZE * 4);

        // A far corner (well outside any inscribed circle) must be transparent...
        let corner = 0; // pixel (0,0)
        assert_eq!(sun[corner * 4 + 3], 0, "sun's corner should be transparent");
        assert_eq!(moon[corner * 4 + 3], 0, "moon's corner should be transparent");

        // ...while dead center is fully opaque and the two textures differ
        // (a warm sun vs. a pale moon), so a custom-texture regression can't
        // silently swap them.
        let center = SKY_TEXTURE_SIZE / 2;
        let ci = (center * SKY_TEXTURE_SIZE + center) * 4;
        assert_eq!(sun[ci + 3], 255);
        assert_eq!(moon[ci + 3], 255);
        assert!(sun[ci] > sun[ci + 2] + 40, "the sun's center should read warm/gold, not neutral gray");
    }

    #[test]
    fn load_custom_sky_texture_returns_none_when_the_file_is_missing() {
        assert!(load_custom_sky_texture(Path::new("/nonexistent/dir"), "sun").is_none());
    }

    #[test]
    fn new_moon_is_fully_dark_and_full_moon_is_fully_lit() {
        for &(nx, ny) in &[(0.0, 0.0), (0.9, 0.0), (0.0, 0.9), (-0.9, -0.9)] {
            assert!(!moon_lit(nx, ny, 0), "new moon should have nothing lit at ({nx}, {ny})");
            assert!(moon_lit(nx, ny, 4), "full moon should have everything lit at ({nx}, {ny})");
        }
    }

    #[test]
    fn quarter_phases_split_the_disc_exactly_in_half_along_the_equator() {
        // At the equator (ny=0) a quarter's terminator is an exact vertical
        // line (cos(PI/2)==0), so this is the one height where a plain
        // sign check is meaningful without float slop from the curve.
        assert!(!moon_lit(-0.5, 0.0, 2), "first quarter: west half should be dark");
        assert!(moon_lit(0.5, 0.0, 2), "first quarter: east half should be lit");
        assert!(moon_lit(-0.5, 0.0, 6), "last quarter: west half should be lit");
        assert!(!moon_lit(0.5, 0.0, 6), "last quarter: east half should be dark");
    }

    #[test]
    fn waxing_phases_are_lit_toward_the_east_and_waning_toward_the_west() {
        // Deep in the "far" horizontal extreme opposite of the growth
        // direction, a thin crescent/gibbous should be unambiguous.
        assert!(moon_lit(0.95, 0.0, 1), "waxing crescent should show a lit sliver in the east");
        assert!(!moon_lit(-0.95, 0.0, 1), "waxing crescent's west edge should stay dark");
        assert!(!moon_lit(-0.95, 0.0, 3), "waxing gibbous's dark sliver should be in the west");
        assert!(moon_lit(0.95, 0.0, 3), "waxing gibbous should be lit almost everywhere else");

        assert!(moon_lit(-0.95, 0.0, 7), "waning crescent should show a lit sliver in the west");
        assert!(!moon_lit(0.95, 0.0, 7), "waning crescent's east edge should stay dark");
        assert!(!moon_lit(0.95, 0.0, 5), "waning gibbous's dark sliver should be in the east");
        assert!(moon_lit(-0.95, 0.0, 5), "waning gibbous should be lit almost everywhere else");
    }

    #[test]
    fn the_terminator_curves_with_the_disc_instead_of_cutting_a_flat_chord() {
        // A flat vertical chord would put the lit/dark boundary at the same
        // nx for every ny. The real (elliptical) terminator's threshold is
        // `cos(theta) * sqrt(1 - ny^2)` - it shrinks toward 0 away from the
        // equator, so a fixed nx that's dark at the equator can cross into
        // lit territory further out, which a flat chord never would.
        assert!(!moon_lit(0.5, 0.0, 1), "x=0.5 should be dark at the equator (< cos(PI/4))");
        assert!(moon_lit(0.5, 0.75, 1), "the same x should be lit further out, as the threshold shrinks");
    }

    #[test]
    fn mask_moon_phase_only_ever_removes_pixels_never_adds_them() {
        let base = generate_moon_pixels(SKY_TEXTURE_SIZE);
        for phase in 0..8u8 {
            let masked = mask_moon_phase(&base, SKY_TEXTURE_SIZE as u32, phase);
            assert_eq!(masked.len(), base.len());
            for i in (3..masked.len()).step_by(4) {
                assert!(masked[i] == 0 || masked[i] == base[i], "phase {phase}: masking must not invent new opacity");
                if base[i] == 0 {
                    assert_eq!(masked[i], 0, "phase {phase}: already-transparent pixels must stay transparent");
                }
            }
        }
        // New moon: literally nothing survives masking.
        let new_moon = mask_moon_phase(&base, SKY_TEXTURE_SIZE as u32, 0);
        assert!(new_moon.iter().skip(3).step_by(4).all(|&a| a == 0));
        // Full moon: masking is a no-op - every already-opaque pixel stays opaque.
        let full_moon = mask_moon_phase(&base, SKY_TEXTURE_SIZE as u32, 4);
        assert_eq!(full_moon, base);
    }
}
